CREATE DATABASE sp_lele;
USE sp_lele;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),password VARCHAR(50),role ENUM('admin','user'));
INSERT INTO users VALUES (1,'admin','admin','admin');

CREATE TABLE penyakit (id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100));
CREATE TABLE gejala (id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100));
CREATE TABLE relasi (id INT AUTO_INCREMENT PRIMARY KEY,gejala_id INT,penyakit_id INT);

CREATE TABLE solusi (id INT AUTO_INCREMENT PRIMARY KEY,penyakit_id INT,deskripsi TEXT);

CREATE TABLE riwayat (id INT AUTO_INCREMENT PRIMARY KEY,user VARCHAR(50),hasil TEXT,tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
